### ISSUE TITLE
svg images

### ISSUE THREAD

**Issue by sandroden** [eKoopmans/html2pdf#185]
I started using html2pdf and appreciated how powerful it is. I wasn't able to reproduce svg images thought and I don't understand if it's a problem of configuration, plugin or what else. I do see jpg and png images.  Any hint is appreciated. Thanks in advance. BTW: I tried to create a jsfiddle, but in that fiddle, I couldn't even see the png and jpg images and that means I miss something fundamental...

**Comment by AbelVM** [comment]
This issue might help you: https://github.com/niklasvh/html2canvas/issues/1578

**Comment by sandroden** [comment]
Thanks @AbelVM  for the pointer, I just tried adding width and height but it didn't solve the issue.

**Comment by sandroden** [comment]
It took me a while to understand that there was an option named 'onclone' *;-) Nevertheless, this was not enough for me. I amanaged to bypass the problem using png images...

**Comment by eKoopmans** [comment]
Hi, thanks @AbelVM for helping out. @sandroden it sounds like your issue was resolved, albeit not in a way that got SVG working. I'm going to close, but please reopen if you want to investigate the SVG issue further.

For anyone else visiting, I haven't tested but from @AbelVM's comments I'd recommend trying:
```js
html2pdf().set({
    html2canvas: {
        onclone: (element) => {
            const svgElements = Array.from(element.querySelectorAll('svg'));
            svgElements.forEach(s => {
                const bBox = s.getBBox();
                s.setAttribute("x", bBox.x);
                s.setAttribute("y", bBox.y);
                s.setAttribute("width", bBox.width);
                s.setAttribute("height", bBox.height);
          }
     }
})... // Whatever else you want to do.
```

**Comment by danksch** [comment]
The above didn't do the trick for me. Anyone else came up with a solution for SVG elements not being displayed in the PDF ?

**Comment by ceerqingting** [comment]
> The above didn't do the trick for me. Anyone else came up with a solution for SVG elements not being displayed in the PDF ?

me too, both width or x doesn't work for me

**Comment by AlissonRS** [comment]
@AbelVM @eKoopmans thanks, that solution in "onclone" callback worked for me.

**Comment by sandhyakhadakhade** [comment]
I tried to resolve this issue but it didn't solve issue. **html2canvas.js?c0e9:2424 1776c1e1438 3960ms Error loading image**

**Comment by NicholasSaravia** [comment]
I was still having trouble with the svg being oversized and this did the trick for me. Thanks to @eKoopmans start code and a small edit I did. here is another solution. ![image](https://user-images.githubusercontent.com/24899931/111836438-a782b880-88cc-11eb-9162-2471fb1ab9c4.png)

**Comment by erensertkaya** [comment]
> Hi, thanks @AbelVM for helping out. @sandroden it sounds like your issue was resolved, albeit not in a way that got SVG working. I'm going to close, but please reopen if you want to investigate the SVG issue further.
> 
> For anyone else visiting, I haven't tested but from @AbelVM's comments I'd recommend trying:
> 
> ```js
> html2pdf().set({
>     html2canvas: {
>         onclone: (element) => {
>             const svgElements = Array.from(element.querySelectorAll('svg'));
>             svgElements.forEach(s => {
>                 const bBox = s.getBBox();
>                 s.setAttribute("x", bBox.x);
>                 s.setAttribute("y", bBox.y);
>                 s.setAttribute("width", bBox.width);
>                 s.setAttribute("height", bBox.height);
>           }
>      }
> })... // Whatever else you want to do.
> ```

Thank you for answer it made my day but there is a problem on bracets i fixed it.
`            html2canvas: {
                onclone: (element) => {
                    const svgElements = Array.from(element.querySelectorAll('svg'));
                    svgElements.forEach(s => {
                        const bBox = s.getBBox();
                        s.setAttribute("x", bBox.x);
                        s.setAttribute("y", bBox.y);
                        s.setAttribute("width", bBox.width);
                        s.setAttribute("height", bBox.height);
                    })
                }
            }`

**Comment by ChadJPetersen** [comment]
To anyone that finds this. I have found this issue quite helpful.
https://github.com/niklasvh/html2canvas/issues/1803

**Comment by akromicc** [comment]
for anyone encountering the problem just add the width and height attributes to the svg example witdh="100"

**Comment by madagaga** [comment]
This worked for me : 
```javascript
html2canvas: {
    onclone: (element) => {
        const svgElements = Array.from(element.querySelectorAll('svg'));
        svgElements.forEach(s => {
            s.setAttribute("width", s.clientWidth);
            s.setAttribute("height", s.clientHeight);
        });
    }
},
```
